version: '3'

services:
  data-flow-db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "15432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  data-flow-redis:
    image: redis
    ports: 
      - "16379:6379"

  data-flow:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "8793:8793"
    env_file: .env
    links:
      - "data-flow-db"
      - "data-flow-redis"
