version: '3'

services:
  data-flow-db:
    image: postgres:10
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "15432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  data-flow-redis:
    image: redis
    ports:
      - "16379:6379"

  data-flow-worker-tensorflow:
    build:
      context: .
      dockerfile: Dockerfile-tensorflow
    volumes:
      - .:/home/vcap/app
    env_file: .env
    links:
      - "data-flow-db"
      - "data-flow-redis"
    entrypoint:
      - airflow
      - worker
      - --queues
      - tensorflow
      - --concurrency
      - "1"

  data-flow-worker-high-memory:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/vcap/app
    env_file: .env

    command:
      - /bin/sh
      - -c
      - |
          airflow worker --queues high-memory-usage --concurrency 1
    links:
      - "data-flow-db"
      - "data-flow-redis"

  data-flow:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/home/vcap/app
    ports:
      - "8080:8080"
      - "8793:8793"
      - "5555:5555"
    env_file: .env

    command:
      - /bin/sh
      - -c
      - |
          airflow initdb
          alembic upgrade head
          ./bin/airflow-scheduler.sh &
          airflow worker &
          airflow flower &
          airflow webserver --pid /tmp/airflow-webserver.pid -p 8080
    links:
      - "data-flow-db"
      - "data-flow-redis"

networks:
  default:
    name: data-infrastructure-shared-network
