version: '3.4'

services:
  data-flow-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-flow-test
    env_file: .env.test
    links:
      - "data-flow-db-test"
    command:
      - /bin/bash
      - -c
      - |
          dockerize -wait tcp://data-flow-db-test:5432
          airflow initdb
          alembic upgrade head
          airflow webserver --pid /tmp/airflow-webserver.pid -p 8080 &
          dockerize -wait tcp://localhost:8080
          pytest tests/integration

  data-flow-db-test:
    build:
      context: .
      dockerfile: ./postgres/Dockerfile
    ports:
      - "15432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
